const router = require("express").Router();
const Utils = require("./utils");
const CustomerRoutes = require("./AuthRoutes/auth");
const HotelRoutes = require("./HotelRoutes/hotel");
const VerifyRoutes = require("./AuthRoutes/verification");
const RoomTypeRoutes = require("./HotelRoutes/roomType");
const AmenitiesRoutes = require("./HotelRoutes/amenities");
const AdminRoutes = require("./admin/adminRoutes");
const FacilitiesRoutes = require("./HotelRoutes/facilitiesRoutes");
const kycRoutes = require("./HotelRoutes/kycroutes");
const Reviews = require("./Reviews/ReviewsRoutes");
const PropertyCateRoutes = require("./HotelRoutes/propertyTypesRoutes");
const NotificationRoutes = require("./notifications/notificationsRoutes");
const MultiTableRoutes = require("./multiTableDataApi");
const AgentRouters = require("./Agentroutes/index");
const StripeGateway = require("./stripe");
const FaqRoutes = require("./Faq");
const PopularLocationRoutes = require("./PopularLocations");
const GoogleRoutes = require("./MiscellaneousRoutes/GoogleRoutes");
const DynamicImageSliderRoutes = require("./DynamicSliderRoutes");
const CCAvenue = require("./CcAvenue");
const OfferRoutes = require("./OffersRoutes.js/offersRoutes");
const EmailEventRoutes = require("./notifications/EmailEventsRoutes");

router.use("/util", Utils);
router.use("/api", CustomerRoutes);
router.use("/api", StripeGateway);
router.use("/api/agent", AgentRouters);
router.use("/hotel", HotelRoutes);
router.use("/admin", AdminRoutes);
// routerverfication related apis
router.use("/verify", VerifyRoutes);
router.use("/roomtype", RoomTypeRoutes);
router.use("/google", GoogleRoutes);
router.use("/amenity", AmenitiesRoutes);
router.use("/facility", FacilitiesRoutes);
router.use("/property-type", PropertyCateRoutes);
router.use("/kyc", kycRoutes);
router.use("/notify", NotificationRoutes);
router.use("/api", MultiTableRoutes);
router.use("/ccav", CCAvenue);
router.use("/faq", FaqRoutes);
router.use("/reviews", Reviews);
router.use("/popular-location", PopularLocationRoutes);
router.use("/slider", DynamicImageSliderRoutes);
router.use("/offers", OfferRoutes);
router.use("/email", EmailEventRoutes);

module.exports = router;
